name: Test deploy
# Runs on all PR events to verify build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: my-website/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: my-website
      - name: Test build website
        run: npm run build
        working-directory: my-website
